image: openjdk

pipelines:
  default:
    - parallel:
      - step:
          name: 'Build and Test'
          script:
            - echo "Your build and test goes here..."
      - step:       
          name: 'Lint'
          script:
            - echo "Your linting goes here..."     
    - parallel:
      - step:
          name: 'Security scan'
          script:
            - echo "Security scan done!"
      - step:
          name: ThreatScan
          services: [docker]
          script:
            - >
              docker run -v $(pwd):/app  threatrix/threatrix-scan
